### ISSUE TITLE
PowerUsage not working

### ISSUE THREAD

**Issue by giacomo270197** [crownstone/bluenet-python-lib#5]
I tried monitoring the power usage of a Crownstone connected to my laptop. This is the code I am using to do so:

```
import json
import sys

from BluenetLib import BluenetEventBus, Topics
from BluenetLib.BLE import BluenetBle

import connect_to_stone


def get_me_data(data):
    print("Getting stuff")
    print(json.dumps(data, indent=2))


ble = BluenetBle(hciIndex=0)
ble.loadSettingsFromFile("keys.json")

sevents = [BluenetEventBus.subscribe(Topics.advertisement, get_me_data),
           BluenetEventBus.subscribe(Topics.crownstoneAvailable, get_me_data),
           BluenetEventBus.subscribe(Topics.newCrownstoneFound, get_me_data),
           BluenetEventBus.subscribe(Topics.powerUsageUpdate, get_me_data)]

connect_to_stone.connect_to_stone(ble, sys.argv[1])
ble.control.setSwitchState(int(sys.argv[2]))

ble.getCrownstonesByScanning(10)

for i in sevents:
    BluenetEventBus.unsubscribe(i)

ble.disconnect()
ble.shutDown()
```
I scan after turning on the stone in order to give time to the EventBus to return data (rather than freezing the thread).
We do manage to get data by plugging another crownstone in. Following is the output:

```
Getting stuff
{
  "name": "Crown",
  "rssi": -75,
  "address": "fc:3a:09:24:3e:91",
  "serviceUUID": 49153,
  "serviceData": {
    "opCode": 6,
    "dataType": 98,
    "stateOfExternalCrownstone": false,
    "hasError": true,
    "setupMode": true,
    "id": 0,
    "switchState": 52,
    "flagsBitmask": 30,
    "temperature": 42,
    "powerFactor": -0.4330708661417323,
    "powerUsageReal": -2081.5,
    "powerUsageApparent": 4806.372727272727,
    "accumulatedEnergy": -1279573329,
    "timestamp": -1,
    "dimmingAvailable": false,
    "dimmingAllowed": true,
    "switchLocked": true,
    "switchCraftEnabled": false,
    "errorMode": false,
    "errors": {
      "overCurrent": false,
      "overCurrentDimmer": false,
      "temperatureChip": false,
      "temperatureDimmer": false,
      "dimmerOnFailure": false,
      "dimmerOffFailure": false,
      "bitMask": 0
    },
    "uniqueElement": 100,
    "timeIsSet": true,
    "deviceType": "PLUG",
    "rssiOfExternalCrownstone": 0
  }
}
Connecting...
Connected
Disconnecting... Cleaning up
Cleaned up
```
This means that `Topics.advertisement` at least works. 
 We were expecting a similar behaviour from `Topics.powerUsageUpdate`.

**Comment by mrquincle** [comment]
We are very busy with the launch in the US. We will look into next week. However, if you need power usage you can already extract it from the advertisement topic yourself very easily (see the fields in the struct you printed). Hence, there's no issue that prevents you from working with this data for now.

**Comment by vliedel** [comment]
Confirmed bug.
Seems like `broadcastState()` is only called from the UART parser, not the BLE parser.

**Comment by AlexDM0** [comment]
Hi Giacomo,

Sorry it took me this long to reply! I have gone through our library and cleaned it up a a bit!

The way the topics worked was confusing and I've tried to unify their format as well as to separate the sources to avoid confusion (hopefully!).

Instead of the topics you have been using, there is now one topic that I'd recommend:
Topics.newDataAvailable

This is only used by the BLE side of the lib, if you're using the USB side (which is not with a random USB dongle, but with our Crownstone USB devices), then you'd need the UsbTopics.newDataAvailable. From your issue I'll assume you're just using the BLE part.

I have also updated the documentation, which will reflect these new topics.

In your case, you can just take the powerUsageReal from the newDataAvailable topic if you want to know the power usage in Watt.

Please update your lib to the 0.6.0 release and let me know if you encounter any issues!

Regards,

Alex
