### ISSUE TITLE
Expected behaviour within BroadcastHandler.py unclear

### ISSUE THREAD

**Issue by hillstub** [crownstone/bluenet-python-lib#9]
When you look at `BroadcastHandler.py` there are several functions to change the state of the Crownstone. I assume the limits are between 0 and 100. However, `turnOnCrownstone` calls `_switchCrownstone` with `255`. That's not the end of the world, though...

However, there is a seemingly bug where one is unable to put the brightness to e.g. 50%. The function `switchCrownstone` converts the input state to a value between 0 and 100, but this is done again in `_switchCrownstone`. This means that if I'd like to set the brightness to 50%, that's not possible:
```
# in switchCrownstone
convertedSwitchState = int(min(1, max(0, 0.5)) * 100)
# convertedSwitchState = 50
self._switchCrownstone(sphereUID, crownstoneId, convertedSwitchState)
```
then in `_switchCrownstone`:
```
convertedSwitchState = int(min(1, max(0, 50)) * 100)
# convertedSwitchState = 100
```
I guess deleting line 20 should fix this issue.

**Comment by AlexDM0** [comment]
Hi there! Thanks for posting the issue! You're right that this should not be done twice. We're currently in the process of splitting up the libraries into individual parts.

https://github.com/crownstone/crownstone-lib-python-core
https://github.com/crownstone/crownstone-lib-python-ble

some of them are on pip at the moment, the BLE one still needs a little work to get it up to speed. The bluenet-python-lib will not receive further updates, all fixes will end up in the cronwstone-lib-python-ble.

I'll update the examples and documentation for you. I'd be happy to hear if the issue is solved using the new library!

Cheers

**Comment by hillstub** [comment]
Hi Alex,
Thanks for your response! I actually started off in the `crownstone-lib-python-ble` repository but then the instruction to `sudo python3 setupBLE.py install` threw me off. Searching for this `setupBLE.py` file led me to this repository ;-).

Enfin, using the proper library indeed helped! Thanks a lot! 

Kudos on a great product, btw!!

**Comment by hillstub** [comment]
Hi Alex,
Thanks! When I run the script now it gives the following error:

```
Traceback (most recent call last):
  File "example_switch_crownstone_via_broadcast.py", line 31, in <module>
    core.broadcast.switchCrownstone(sphereUID, crownstoneId, state)
  File "/usr/local/lib/python3.7/dist-packages/crownstone_ble-0.5.0-py3.7.egg/crownstone_ble/core/ble_modules/BroadcastHandler.py", line 24, in switchCrownstone
  File "/usr/local/lib/python3.7/dist-packages/crownstone_ble-0.5.0-py3.7.egg/crownstone_ble/core/ble_modules/BroadcastHandler.py", line 36, in _switchCrownstone
NameError: name 'convertedSwitchState' is not defined
```

I guess you forgot to update the appropriate parameter int the function definition of `_switchCrownstone`. ;-)

Best,

**Comment by AlexDM0** [comment]
yes... good point. Sorry for the sloppy fix. Should be working now.

Thanks for pointing out the problem :)
